# @File: config.dev.yaml
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2023-09-29

gitconfig:
  username: AustinFairyland
  email: fairylandhost@outlook.com
  token: 
gitrepo:
  reponame: test_auto_push
  giturl: git@github.com:AustinFairyland/test_auto_push.git
  httpurl: https://github.com/AustinFairyland/test_auto_push.git
